const FLIGHTS = [
    { number: 'AI-101', airline: 'Air India', source: 'AMD', destination: 'BOM', departure: '10:30 AM', arrival: '11:45 AM', gate: 'A12', terminal: '2', status: 'Boarding' },
    { number: '6E-245', airline: 'IndiGo', source: 'DEL', destination: 'BLR', departure: '12:15 PM', arrival: '03:05 PM', gate: 'B04', terminal: '1', status: 'Scheduled' },
    { number: 'UK-832', airline: 'Vistara', source: 'BOM', destination: 'DEL', departure: '02:40 PM', arrival: '04:55 PM', gate: 'C08', terminal: '2', status: 'Delayed' },
    { number: 'AI-202', airline: 'Air India', source: 'AMD', destination: 'DEL', departure: '04:20 PM', arrival: '06:05 PM', gate: 'A08', terminal: '1', status: 'Scheduled' },
    { number: '6E-711', airline: 'IndiGo', source: 'AMD', destination: 'HYD', departure: '06:10 PM', arrival: '08:00 PM', gate: 'B11', terminal: '1', status: 'Scheduled' },
    { number: 'SG-405', airline: 'SpiceJet', source: 'BOM', destination: 'AMD', departure: '08:30 PM', arrival: '09:55 PM', gate: 'C12', terminal: '2', status: 'Boarding' }
];
const PASSENGERS = [
    { id: 'P1001', name: 'Rahul Patel', flight: 'AI-101', seat: '12A', group: 'A', priority: 2, type: 'Senior Citizen', status: 'Boarded' },
    { id: 'P1002', name: 'Priya Shah', flight: 'AI-101', seat: '16C', group: 'B', priority: 5, type: 'Normal', status: 'Waiting' },
    { id: 'P1003', name: 'Aarav Mehta', flight: 'AI-101', seat: '08B', group: 'A', priority: 3, type: 'Child', status: 'Waiting' },
    { id: 'P1004', name: 'Neha Patel', flight: 'AI-101', seat: '04A', group: 'A', priority: 1, type: 'Special Assistance', status: 'Waiting' },
    { id: 'P1005', name: 'Rohan Desai', flight: '6E-245', seat: '21D', group: 'C', priority: 5, type: 'Normal', status: 'Boarded' },
    { id: 'P1006', name: 'Isha Joshi', flight: '6E-245', seat: '09F', group: 'A', priority: 2, type: 'Senior Citizen', status: 'Boarded' },
    { id: 'P1007', name: 'Vikram Singh', flight: '6E-245', seat: '14B', group: 'B', priority: 4, type: 'Normal', status: 'Waiting' },
    { id: 'P1008', name: 'Kavya Rao', flight: 'UK-832', seat: '02A', group: 'A', priority: 1, type: 'Special Assistance', status: 'Waiting' },
    { id: 'P1009', name: 'Aditya Shah', flight: 'UK-832', seat: '18C', group: 'B', priority: 5, type: 'Normal', status: 'Not Boarded' },
    { id: 'P1010', name: 'Meera Patel', flight: 'UK-832', seat: '07D', group: 'A', priority: 3, type: 'Child', status: 'Waiting' },
    { id: 'P1011', name: 'Dhruv Mehta', flight: 'AI-101', seat: '25E', group: 'C', priority: 4, type: 'Normal', status: 'Boarded' },
    { id: 'P1012', name: 'Ananya Desai', flight: '6E-245', seat: '11A', group: 'B', priority: 2, type: 'Senior Citizen', status: 'Waiting' },
    { id: 'P1013', name: 'Harsh Shah', flight: 'UK-832', seat: '30F', group: 'C', priority: 5, type: 'Normal', status: 'Waiting' },
    { id: 'P1014', name: 'Siya Joshi', flight: 'AI-101', seat: '05B', group: 'A', priority: 1, type: 'Special Assistance', status: 'Boarded' }
];
function data(k, seed) { try { const x = JSON.parse(localStorage.getItem(k)); if (Array.isArray(x)) return x } catch (e) { } localStorage.setItem(k, JSON.stringify(seed)); return seed.map(x => ({ ...x })) }
function save(k, v) { localStorage.setItem(k, JSON.stringify(v)) }
function esc(v) { return String(v ?? '').replace(/[&<>"']/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[m])) }
function badge(s) { return `<span class="badge ${s === 'Boarded' || s === 'Boarding' ? 'green' : s === 'Delayed' ? 'orange' : 'blue'}">${esc(s)}</span>` }
function dashboard() { const f = data('flights', FLIGHTS), p = data('passengers', PASSENGERS), c = document.querySelectorAll('.stat-card strong'); if (c.length >= 6) { c[0].textContent = f.length; c[1].textContent = p.length; c[2].textContent = p.filter(x => x.status === 'Boarded').length; c[3].textContent = p.filter(x => x.status === 'Waiting').length; c[4].textContent = f.filter(x => x.status === 'Boarding' || x.status === 'Scheduled').length; c[5].textContent = f.filter(x => x.status === 'Delayed').length } }
function renderFlights() { const t = document.querySelector('.table-wrap tbody'); if (!t || !location.pathname.endsWith('flights.html')) return; const f = data('flights', FLIGHTS); t.innerHTML = f.map(x => `<tr><td><b>${esc(x.number)}</b></td><td>${esc(x.airline)}</td><td>${esc(x.source)}</td><td>${esc(x.destination)}</td><td>${esc(x.departure)}</td><td>${esc(x.gate)}</td><td>${badge(x.status)}</td><td><button class="small-btn delete-flight" data-id="${esc(x.number)}">Delete</button></td></tr>`).join(''); t.querySelectorAll('.delete-flight').forEach(b => b.onclick = () => { save('flights', data('flights', FLIGHTS).filter(x => x.number !== b.dataset.id)); renderFlights(); dashboard() }) }
function renderPassengers() { const t = document.querySelector('.table-wrap tbody'); if (!t || !location.pathname.endsWith('passengers.html')) return; const p = data('passengers', PASSENGERS); t.innerHTML = p.map(x => `<tr><td><b>${esc(x.id)}</b></td><td>${esc(x.name)}</td><td>${esc(x.flight)}</td><td>${esc(x.seat)}</td><td>${esc(x.group)}</td><td>${x.priority}</td><td>${esc(x.type)}</td><td>${badge(x.status)}</td><td><button class="small-btn delete-passenger" data-id="${esc(x.id)}">Delete</button></td></tr>`).join(''); t.querySelectorAll('.delete-passenger').forEach(b => b.onclick = () => { save('passengers', data('passengers', PASSENGERS).filter(x => x.id !== b.dataset.id)); renderPassengers(); dashboard() }) }
function forms() { const card = document.querySelector('.form-card'); if (!card) return; const v = card.querySelectorAll('input,select'), btn = card.querySelector('.primary-btn'); btn?.addEventListener('click', () => { const a = [...v].map(x => x.value.trim()); if (location.pathname.endsWith('flights.html')) { if (!a[0] || !a[1]) return alert('Enter Flight Number and Airline.'); const d = data('flights', FLIGHTS); if (d.some(x => x.number === a[0])) return alert('Flight already exists.'); d.push({ number: a[0], airline: a[1], source: a[2] || '—', destination: a[3] || '—', departure: a[4] || '—', arrival: a[5] || '—', gate: a[6] || '—', terminal: a[7] || '—', status: a[8] || 'Scheduled' }); save('flights', d); renderFlights(); alert('Flight added.') } else if (location.pathname.endsWith('passengers.html')) { if (!a[0] || !a[1]) return alert('Enter Passenger ID and Name.'); const d = data('passengers', PASSENGERS); if (d.some(x => x.id === a[0])) return alert('Passenger ID already exists.'); d.push({ id: a[0], name: a[1], flight: a[2] || 'AI-101', seat: a[3] || '—', group: a[4] || 'A', priority: parseInt(String(a[5]).replace(/\D/g, ''), 10) || 5, type: a[6] || 'Normal', status: a[7] || 'Waiting' }); save('passengers', d); renderPassengers(); alert('Passenger added.') } }) }
function boarding() { if (!location.pathname.endsWith('boarding.html')) return; const t = document.querySelector('.table-wrap tbody'); if (!t) return; const p = data('passengers', PASSENGERS), w = p.filter(x => x.status === 'Waiting'); const boarded = p.filter(x => x.status === 'Boarded').length, waiting = w.length, notBoarded = p.filter(x => x.status === 'Not Boarded').length, total = p.length, percent = total ? ((boarded / total) * 100) : 0; document.getElementById('boardedCount').textContent = boarded + ' / ' + total; document.getElementById('boardingProgress').style.width = percent.toFixed(1) + '%'; document.getElementById('boardingPercent').textContent = percent.toFixed(1) + '%'; document.getElementById('totalCount').textContent = total; document.getElementById('waitingCount').textContent = waiting; document.getElementById('notBoardedCount').textContent = notBoarded; document.getElementById('boardedOnly').textContent = boarded; t.innerHTML = w.map(x => `<tr><td><b>${esc(x.id)}</b> ${esc(x.name)}</td><td>${esc(x.flight)}</td><td>${esc(x.seat)}</td><td>${x.priority}</td><td>${esc(x.type)}</td><td>${esc(x.status)}</td><td><button class="small-btn board" data-id="${x.id}">Board Passenger</button></td></tr>`).join(''); t.querySelectorAll('.board').forEach(b => b.onclick = () => { const d = data('passengers', PASSENGERS), x = d.find(y => y.id === b.dataset.id); if (x) x.status = 'Boarded'; save('passengers', d); boarding(); dashboard() }) }
function linearSearch() { if (!location.pathname.endsWith('search.html')) return; const q = document.querySelector('.search-line input'), btn = document.querySelector('.search-line button'), r = document.querySelector('.result'), list = document.getElementById('searchResults'), count = document.getElementById('searchResultCount'); btn?.addEventListener('click', () => { const s = q.value.trim().toLowerCase(), p = data('passengers', PASSENGERS); let matches = [], c = 0; const st = performance.now(); for (let i = 0; i < p.length; i++) { c++; const x = p[i], values = [x.id, x.name, x.flight, x.seat, x.group, x.priority, x.type, x.status].map(v => String(v ?? '').toLowerCase()); if (!s || values.some(v => v.includes(s))) matches.push(x) } const elapsed = (performance.now() - st).toFixed(4); r.innerHTML = `Result: <b>${matches.length ? 'Found' : 'Not Found'}</b><br>Comparisons: ${c}<br>Execution time: ${elapsed} ms`; count.textContent = `${matches.length} passenger${matches.length === 1 ? '' : 's'} found`; list.innerHTML = matches.length ? matches.map(x => `<article class="search-found-card"><div><strong>${esc(x.name)}</strong><span>${esc(x.id)} · ${esc(x.status)}</span></div><dl><div><dt>Flight</dt><dd>${esc(x.flight)}</dd></div><div><dt>Seat</dt><dd>${esc(x.seat)}</dd></div><div><dt>Boarding group</dt><dd>${esc(x.group)}</dd></div><div><dt>Priority</dt><dd>${esc(x.priority)}</dd></div><div><dt>Passenger type</dt><dd>${esc(x.type)}</dd></div></dl></article>`).join('') : '<div class="linear-empty">No passengers matched. Try another name, ID, flight, seat, or status.</div>' }) }
function quickSortPage() { if (!location.pathname.endsWith('sorting.html')) return; let p = data('passengers', PASSENGERS), t = document.getElementById('passengerTable'); if (!t) return; const value = (x, f) => f === 'priority' ? +x.priority : f === 'id' ? +(x.id.replace(/\D/g, '')) : f === 'seat' ? +(x.seat.replace(/\D/g, '')) : String(x[f] ?? '').toLowerCase(); function qs(a, f, d, s) { function cmp(x, y) { const A = value(x, f), B = value(y, f); let r = typeof A === 'number' && typeof B === 'number' ? A - B : A < B ? -1 : A > B ? 1 : 0; return d === 'asc' ? r : -r } function part(l, h) { const pv = a[h]; let i = l - 1; for (let j = l; j < h; j++) { s.c++; if (cmp(a[j], pv) <= 0) { i++;[a[i], a[j]] = [a[j], a[i]]; s.sw++ } } [a[i + 1], a[h]] = [a[h], a[i + 1]]; s.sw++; return i + 1 } function rec(l, h) { if (l < h) { const m = part(l, h); rec(l, m - 1); rec(m + 1, h) } } rec(0, a.length - 1); return a } function render() { t.innerHTML = p.map(x => `<tr><td><b>${esc(x.id)}</b></td><td>${esc(x.name)}</td><td>${esc(x.flight)}</td><td>${esc(x.seat)}</td><td>${esc(x.group)}</td><td><b>${x.priority}</b></td><td>${esc(x.type)}</td><td>${badge(x.status)}</td></tr>`).join(''); document.getElementById('recordCount').textContent = p.length } render(); document.getElementById('runSort')?.addEventListener('click', () => { let f = document.getElementById('sortField').value, d = document.getElementById('sortOrder').value, q = document.getElementById('queueMode').value; if (q === 'priority') { f = 'priority'; d = 'asc' } if (q === 'priorityDesc') { f = 'priority'; d = 'desc' } const s = { c: 0, sw: 0 }, st = performance.now(); p = qs(p.map(x => ({ ...x })), f, d, s); save('passengers', p); render(); document.getElementById('comparisonCount').textContent = s.c; document.getElementById('swapCount').textContent = s.sw; document.getElementById('executionTime').textContent = (performance.now() - st).toFixed(4) + ' ms' }); document.getElementById('resetSort')?.addEventListener('click', () => { p = PASSENGERS.map(x => ({ ...x })); save('passengers', p); render(); document.getElementById('comparisonCount').textContent = 0; document.getElementById('swapCount').textContent = 0; document.getElementById('executionTime').textContent = '0 ms' }) }
document.addEventListener('DOMContentLoaded', () => { data('flights', FLIGHTS); data('passengers', PASSENGERS); dashboard(); renderFlights(); renderPassengers(); forms(); boarding(); linearSearch(); quickSortPage(); document.querySelectorAll('.btn,.search-btn,.search-line button,.small-btn').forEach(b => b.addEventListener('click', e => { const r = b.getBoundingClientRect(), s = document.createElement('span'); s.className = 'js-ripple'; s.style.left = (e.clientX - r.left) + 'px'; s.style.top = (e.clientY - r.top) + 'px'; b.appendChild(s); setTimeout(() => s.remove(), 600) })) });
